### ISSUE TITLE
Can't install addon

### ISSUE THREAD

**Issue by phischmi** [RobocopKlaus/hassio-addon-blocky#15]
Hi,
I just tried installing your addon but Home-Asisstant threw the following error:

> Can't install ghcr.io/robocopklaus/aarch64-addon-blocky:0.2.0: 404 Client Error for http+docker://localhost/v1.44/images/ghcr.io/robocopklaus/aarch64-addon-blocky:0.2.0/json: Not Found ("No such image: ghcr.io/robocopklaus/aarch64-addon-blocky:0.2.0")

Could you please look into this, since I'm very interested in your addon?

I'm running:

Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

Thanks a lot.

BR Philipp

**Comment by RobocopKlaus** [comment]
Hey Philipp, that's weird. I'll have a look ✌️

**Comment by RobocopKlaus** [comment]
Hey @phischmi, I just released a new version. It should work now 🤞😊
