### ISSUE TITLE
Can't install addon

### ISSUE THREAD

**Issue by nodomain** [robocopklaus/hassio-addon-blocky#20]
Can't install ghcr.io/robocopklaus/hassio-addon-blocky-amd64:0.2.1: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/robocopklaus/hassio-addon-blocky-amd64:0.2.1/json: Not Found ("No such image: ghcr.io/robocopklaus/hassio-addon-blocky-amd64:0.2.1")

What am I doing wrong?

**Comment by robocopklaus** [comment]
hey @nodomain, thanks for reporting the issue. I'll have a look at it ✌️

**Comment by robocopklaus** [comment]
hey @nodomain, I've updated the version. It should work now 😊
